# Generated by Django 2.2.14 on 2020-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.IntegerField(max_length=200)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(max_length=200)),
                ('consumo', models.CharField(max_length=200)),
                ('mercancia_Venta', models.CharField(max_length=200)),
                ('produccion_interna', models.CharField(max_length=200)),
                ('maneja_lotes', models.CharField(max_length=200)),
                ('es_servicio', models.CharField(max_length=200)),
                ('producto_activo', models.CharField(max_length=200)),
                ('datos_fabricante', models.CharField(max_length=200)),
                ('medidas', models.CharField(max_length=200)),
                ('ubicacion_fisica', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=200)),
                ('producto_equivalente', models.CharField(max_length=200)),
                ('stock_minimo', models.CharField(max_length=200)),
                ('stock_maximo', models.CharField(max_length=200)),
                ('tiempo_reposicion', models.CharField(max_length=200)),
                ('cuenta_inventario', models.CharField(max_length=200)),
                ('cuenta_contable_ingreso', models.CharField(max_length=200)),
                ('cuenta_contable_ingreso_ajuste', models.CharField(max_length=200)),
                ('devolucion_ventas', models.CharField(max_length=200)),
                ('devolucion_compras', models.CharField(max_length=200)),
                ('cuenta_contable_gasto', models.CharField(max_length=200)),
                ('cuenta_contable_gasto_ajuste', models.CharField(max_length=200)),
                ('venta_impuesto', models.CharField(max_length=200)),
                ('compra_impuesto', models.CharField(max_length=200)),
            ],
        ),
    ]
